#!/bin/bash
echo $(( 8#$(((5#$WATER)+(5#$STIR)))))
tr 'water' '01234' 
$((5#$WATER | tr 'water 01234'))
0 1 2 3 4
W A T E R
S T I R .
0 1 2 3 4 5 6 7
B E H L N O R T
8#(tr ($((5#(tr $WATER 'water' '01234')))+ $((5#(tr $STIR 'stir.' '01234')))) 'behlnort' '01234567')
