#!/bin/bash
echo $(( 8#$(((5#$WATER)+(5#$STIR)))))
tr 'water' '01234' 
$((5#$WATER | tr 'water 01234'))
0 1 2 3 4
W A T E R
S T I R .
0 1 2 3 4 5 6 7
B E H L N O R T
8#(tr ($((5#(tr $WATER 'water' '01234')))+ $((5#(tr $STIR 'stir.' '01234')))) 'behlnort' '01234567')
echo $WATER | tr 'water' '01234' outputs 30012412301
echo $STIR | tr 'stir.' '01234' outputs 12421231313
echo $(( (echo $WATER | tr 'water' '01234') + (echo $STIR | tr 'stir.' '01234') )) 
echo $((5#$WATER | tr 'water 01234')) + 5#$((echo $STIR | tr 'stir.' '01234')) | tr '01234567' 'behlnort'
printf "%o\n" $(( 5#$((echo $WATER | tr 'water 01234')) + 5#$((echo $STIR | tr 'stir.' '01234')) )) | tr '01234567' 'behlnort'
