#!/usr/bin/env bash
# CHINSESE UPERSITITITUOONSS

i=1

while [ $i -lt 11 ]; do
    if [ $i = 4 ]; then
        echo "bad luck"
    elif [ $i = 8 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let i+=1
done
