#!/usr/bin/env bash
# prints cloth things

hour=0

while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]; do
        echo "$min"
        let min+=1
    done
    let hour+=1
done
