#!/usr/bin/env bash
# checks to see if the file exists for stuff.


if [ -e holbertonschool ]; then
    echo 'holbertonschool file exists'
    if [ -s holbertonschool ]; then
        echo 'holbertonschool file is not empty'
    else
        echo 'holbertonschool file is empty'
    fi
    if [ -f holbnertonschool ]; then
        echo 'holbertonschool file is a regular file'
    fi
else
    echo 'holbertonschool file does not exist'
fi
