#!/usr/bin/env bash
# checks to see if the file exists for stuff.

temp="${PWD}/holbertonschool"

if [ -e "$temp" ]; then
    echo holbertonschool file exists
    if [ -s "$temp" ]; then
        echo holbertonschool file is not empty
    else
        echo holbertonschool file is empty
    fi
    if [ -f "$temp" ]; then
        echo holbertonschool file is a regular file
    fi
else
    echo holbertonschool file does not exist
fi
