#!/usr/bin/env bash
# redirects to nyancat
sudo apt-get -y update
sudo apt-get -u upgrade
sudo apt-get -y install nginx
service nginx start
#string="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "32i location /redirect_me {return 301
https://www.youtube.com/watch?v=QH2-TGUlwu4/redirect-this$1;}"
/etc/nginx/sites-available/default
sudo service nginx restart
