#!/usr/bin/env bash
# does things. I used these commands # sudo docker exec -i c70af193f7d0
sudo apt-get -y update
sudo apt-get -y install apache2
#sudo echo "ServerName localhost" >> /etc/apache2/apache2.conf
#sudo service apache2 start
sudo service apache2 restart
