#!/usr/bin/env bash
# run nginx as nginx
pkill -f apache2
chmod 744 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i --follow-symlink "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
